server:
    port: 8091
    context-path: /

# 日志级别,默认的日志实现是logback
logging:
    path: /tmp
    level:
        root: "TRACE"
        com.beta.sb.web.rest.HelloWorldController: "WARN"
    config:
        classpath: logback-spring.xml


common:
    properties:
        name: zhangsan_dev
        title: title_dev